# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'add', 'add2']

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def add(x: int, # number 1 
        y: int, # number 1
        z: int, # number 2
       )->int: # last number
    "returns sum of the three numbers"
    return x + y + z
    

# %% ../nbs/00_core.ipynb 8
def add2(x: int, # number 1 
        y: int, # number 1
        z: int, # number 2
       )->int: # last number
    "returns sum of the three numbers"
    return x + y + z
    
